
server:
  port: 8016


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmodev?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: kjlee
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true


#elasticsearch
elasticsearch:
  dic:
    path: /Users/kjlee/tmp
  host: 15.164.28.71
  port: 9200
